# Generated by Django 3.1.4 on 2020-12-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0002_auto_20201206_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaccounts',
            name='name',
        ),
        migrations.AddField(
            model_name='adminaccounts',
            name='firstname',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminaccounts',
            name='password',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminaccounts',
            name='surname',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminaccounts',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
