# Generated by Django 3.1.4 on 2020-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0003_auto_20201206_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
