# Generated by Django 3.1.4 on 2020-12-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0006_auto_20201211_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminAccount',
            new_name='HelperAccount',
        ),
    ]
