# Generated by Django 3.1.4 on 2020-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0007_auto_20201215_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('game_type', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('username', 'game_type')},
            },
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
