# Generated by Django 3.1.4 on 2020-12-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0008_auto_20201218_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scores',
            new_name='Score',
        ),
    ]
