# Generated by Django 3.1.4 on 2020-12-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0009_auto_20201218_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game_type',
            field=models.CharField(max_length=50),
        ),
    ]
