# Generated by Django 3.1.4 on 2020-12-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0011_auto_20201220_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game_type',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
