# Generated by Django 3.1.4 on 2020-12-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0012_auto_20201220_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
