# Generated by Django 3.1.4 on 2020-12-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0013_auto_20201221_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='username',
            new_name='player_username',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player_username', 'game_type')},
        ),
    ]
