# Generated by Django 3.1.4 on 2020-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFDM', '0015_auto_20201222_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
